# Base configs
baseurl: "https://phongvu2508.github.io/foto"

image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "phongvufoto"
subtitle: "See the world through my eyes!"
author: "Phong Vu"
bio_1: "Just a "
bio_2: " with passion for photography."
bio_job_title: "software developer"
bio_profile_link: "https://phongvu.dev"
bio: "Just a software developer with passion for photography."
publicise: ""
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/phong.vu.758"
  twitter: "https://www.twitter.com/Phong_Vu"
  instagram: "https://www.instagram.com/phongvufoto"
  linkedin: "https://in.linkedin.com/in/phong-vu-software-developer"
  github: "https://www.github.com/phongvu2508"
